

```{r}
# if(!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# BiocManager::install("Maaslin2")
# BiocManager::install("lefser")
# BiocManager::install("DESeq2")
# BiocManager::install("ALDEx2")
# BiocManager::install("phyloseq")
# devtools::install_github("cafferychen777/ggpicrust2")
# options(error = browser) # 设置进入调试模式
library(ggpicrust2)
library(dplyr)
library(patchwork)
library(ggprism)
library(phyloseq)

```

## KO

```{r}
source("my_functions.R")
#If you want to analysis kegg pathway abundance instead of ko within the pathway. You should turn ko_to_kegg to TRUE.
#The kegg pathway typically have the more explainable description.
metadata <- readr::read_delim(
    "new_metadata.txt",
    delim = "\t",
    escape_double = FALSE,
    trim_ws = TRUE
  )
group = "Enviroment"#Mouse_Sex Enviroment
reference="Pro-survival"
# library(httr)
# set_config(config(ssl_verifypeer = 0L))
##########################################run one step##########################################
daa_method = "edgeR" #LinDA  ALDEx2 "limma voom" edgeR DEseq2
daa_results_list <-ggpicrust3(
                    file = "KO_pred_metagenome_unstrat.tsv",
                    metadata = metadata,
                    group = group,
                    pathway = "KO",
                    daa_method = daa_method,
                    order = "pathway_class",
                    ko_to_kegg = TRUE,
                    x_lab = "pathway_name",
                    p.adjust = "BH",
                    p_value_bar = TRUE, #fold change
                    select = "Top 30" , #Top 30
                    reference = reference 
                  )
pdf(paste("daa_results_plot",group,daa_method,".pdf",sep = "_"),width = 18)
# show(daa_results_list[[1]])
show(daa_results_list)
dev.off()
```


```{r}
#################################every step##################################
ko_table<-ko2kegg_abundance(file = "KO_pred_metagenome_unstrat.tsv")
ko_pathway_daa=pathway_daa(abundance=ko_table,metadata=metadata,group=group)
ko_pathway_anno=pathway_annotation(file = "KO_pred_metagenome_unstrat.tsv",daa_results_df=ko_pathway_daa,pathway = "KO",ko_to_kegg = TRUE)
# ko_pathway_daa$description<-ko_pathway_daa$feature
pathway_errorbar3(
                 abundance=ko_table,
                 daa_results_df=ko_pathway_daa,
                 Group=metadata[,group],
                 p_values_threshold=0.03,
                 select=NULL,
                 ko_to_kegg=TRUE,
                 x_lab=NULL,
                 p_value_bar = TRUE)

###################################################################

# Perform PCA and create visualizations
pca_plot <- ggpicrust2::pathway_pca(ko_table, metadata, "Enviroment")


# library(httr)
# set_config(config(ssl_verifypeer = 0L))
###################################################################
ko_table<-ko2kegg_abundance(file = "KO_pred_metagenome_unstrat.tsv")

ko_pathway_daa=pathway_daa(abundance=ko_table,metadata=metadata,group="Enviroment")

ko_pathway_anno=pathway_annotation(file = "KO_pred_metagenome_unstrat.tsv",daa_results_df=ko_pathway_daa,pathway = "KO",ko_to_kegg = TRUE)

pathway_errorbar3(
                 abundance=ko_table,
                 daa_results_df=ko_pathway_daa,
                 Group=metadata$Enviroment,
                 p_values_threshold=0.05,
                 select=NULL,
                 p_value_bar = TRUE,
                 ko_to_kegg = TRUE,
                 colors = NULL,
                  x_lab = NULL)

###################################################################

# Perform PCA and create visualizations
pca_plot <- ggpicrust2::pathway_pca(ko_table, metadata, "Enviroment")
```

##EC

```{r}
source("my_functions.R")
#If you want to analysis the EC. MetaCyc. KO without conversions. You should turn ko_to_kegg to FALSE.
metadata <-
  read_delim(
    "new_metadata.txt",
    delim = "\t",
    escape_double = FALSE,
    trim_ws = TRUE
  )
group <- "Enviroment"
daa_results_list <-
  ggpicrust3(
    file = "pred_metagenome_unstrat.tsv",
    metadata = metadata,
    group = "Enviroment",
    pathway = "EC",
    daa_method = "LinDA",
    order = "group",
    ko_to_kegg = FALSE,
    x_lab = "description",
    p.adjust = "BH",
    select = NULL,
    reference = NULL
  )
#The visualization will be published in viewer.

```





